var annotated_dup =
[
    [ "agm_acdb_param", "structagm__acdb__param.html", "structagm__acdb__param" ],
    [ "agm_acdb_tunnel_param", "structagm__acdb__tunnel__param.html", "structagm__acdb__tunnel__param" ],
    [ "agm_buf_info", "structagm__buf__info.html", "structagm__buf__info" ],
    [ "agm_buff", "structagm__buff.html", "structagm__buff" ],
    [ "agm_buffer_config", "structagm__buffer__config.html", "structagm__buffer__config" ],
    [ "agm_cal_config", "structagm__cal__config.html", "structagm__cal__config" ],
    [ "agm_cshm_info", "structagm__cshm__info.html", "structagm__cshm__info" ],
    [ "agm_dump_info", "structagm__dump__info.html", "structagm__dump__info" ],
    [ "agm_event_cb_params", "structagm__event__cb__params.html", "structagm__event__cb__params" ],
    [ "agm_event_read_write_done_payload", "structagm__event__read__write__done__payload.html", "structagm__event__read__write__done__payload" ],
    [ "agm_event_reg_cfg", "structagm__event__reg__cfg.html", "structagm__event__reg__cfg" ],
    [ "agm_extern_alloc_buff_info", "structagm__extern__alloc__buff__info.html", "structagm__extern__alloc__buff__info" ],
    [ "agm_group_media_config", "structagm__group__media__config.html", "structagm__group__media__config" ],
    [ "agm_key_value", "structagm__key__value.html", "structagm__key__value" ],
    [ "agm_media_config", "structagm__media__config.html", "structagm__media__config" ],
    [ "agm_module_id_iid_map", "structagm__module__id__iid__map.html", "structagm__module__id__iid__map" ],
    [ "agm_msg_config", "structagm__msg__config.html", "structagm__msg__config" ],
    [ "agm_session_aac_dec", "structagm__session__aac__dec.html", "structagm__session__aac__dec" ],
    [ "agm_session_aac_enc", "structagm__session__aac__enc.html", "structagm__session__aac__enc" ],
    [ "agm_session_aac_enc_cfg", "structagm__session__aac__enc__cfg.html", "structagm__session__aac__enc__cfg" ],
    [ "agm_session_alac_dec", "structagm__session__alac__dec.html", "structagm__session__alac__dec" ],
    [ "agm_session_ape_dec", "structagm__session__ape__dec.html", "structagm__session__ape__dec" ],
    [ "agm_session_codec", "unionagm__session__codec.html", "unionagm__session__codec" ],
    [ "agm_session_config", "structagm__session__config.html", "structagm__session__config" ],
    [ "agm_session_flac_dec", "structagm__session__flac__dec.html", "structagm__session__flac__dec" ],
    [ "agm_session_opus_dec", "structagm__session__opus__dec.html", "structagm__session__opus__dec" ],
    [ "agm_session_wma_dec", "structagm__session__wma__dec.html", "structagm__session__wma__dec" ],
    [ "agm_session_wmapro_dec", "structagm__session__wmapro__dec.html", "structagm__session__wmapro__dec" ],
    [ "agm_tag_config", "structagm__tag__config.html", "structagm__tag__config" ],
    [ "agm_tag_info", "structagm__tag__info.html", "structagm__tag__info" ],
    [ "agm_tag_module_info_list", "structagm__tag__module__info__list.html", "structagm__tag__module__info__list" ],
    [ "aif_info", "structaif__info.html", "structaif__info" ],
    [ "prop_data", "structprop__data.html", "structprop__data" ]
];