var annotated_dup =
[
    [ "domain", "structdomain.html", "structdomain" ],
    [ "dspqueue_buffer", "structdspqueue__buffer.html", "structdspqueue__buffer" ],
    [ "dspqueue_create_req", "structdspqueue__create__req.html", "structdspqueue__create__req" ],
    [ "dspqueue_request_payload", "structdspqueue__request__payload.html", "structdspqueue__request__payload" ],
    [ "fastrpc_async_callback", "structfastrpc__async__callback.html", "structfastrpc__async__callback" ],
    [ "fastrpc_async_descriptor", "structfastrpc__async__descriptor.html", "structfastrpc__async__descriptor" ],
    [ "fastrpc_capability", "structfastrpc__capability.html", null ],
    [ "fastrpc_context_create", "structfastrpc__context__create.html", "structfastrpc__context__create" ],
    [ "fastrpc_context_destroy", "structfastrpc__context__destroy.html", "structfastrpc__context__destroy" ],
    [ "remote_arg", "unionremote__arg.html", "unionremote__arg" ],
    [ "remote_arg64", "unionremote__arg64.html", "unionremote__arg64" ],
    [ "remote_buf", "structremote__buf.html", "structremote__buf" ],
    [ "remote_buf64", "structremote__buf64.html", "structremote__buf64" ],
    [ "remote_control_custom_path", "structremote__control__custom__path.html", "structremote__control__custom__path" ],
    [ "remote_dma_handle", "structremote__dma__handle.html", "structremote__dma__handle" ],
    [ "remote_dma_handle64", "structremote__dma__handle64.html", "structremote__dma__handle64" ],
    [ "remote_dsp_capability", "structremote__dsp__capability.html", "structremote__dsp__capability" ],
    [ "remote_process_type", "structremote__process__type.html", "structremote__process__type" ],
    [ "remote_rpc_control_latency", "structremote__rpc__control__latency.html", "structremote__rpc__control__latency" ],
    [ "remote_rpc_control_pd_dump", "structremote__rpc__control__pd__dump.html", "structremote__rpc__control__pd__dump" ],
    [ "remote_rpc_control_unsigned_module", "structremote__rpc__control__unsigned__module.html", "structremote__rpc__control__unsigned__module" ],
    [ "remote_rpc_control_wakelock", "structremote__rpc__control__wakelock.html", "structremote__rpc__control__wakelock" ],
    [ "remote_rpc_effective_domain_id", "structremote__rpc__effective__domain__id.html", "structremote__rpc__effective__domain__id" ],
    [ "remote_rpc_get_domain", "structremote__rpc__get__domain.html", "structremote__rpc__get__domain" ],
    [ "remote_rpc_get_uri", "structremote__rpc__get__uri.html", "structremote__rpc__get__uri" ],
    [ "remote_rpc_notif_register", "structremote__rpc__notif__register.html", "structremote__rpc__notif__register" ],
    [ "remote_rpc_pd_initmem_size", "structremote__rpc__pd__initmem__size.html", "structremote__rpc__pd__initmem__size" ],
    [ "remote_rpc_process_clean_params", "structremote__rpc__process__clean__params.html", "structremote__rpc__process__clean__params" ],
    [ "remote_rpc_relative_thread_priority", "structremote__rpc__relative__thread__priority.html", "structremote__rpc__relative__thread__priority" ],
    [ "remote_rpc_reserve_new_session", "structremote__rpc__reserve__new__session.html", "structremote__rpc__reserve__new__session" ],
    [ "remote_rpc_session_close", "structremote__rpc__session__close.html", "structremote__rpc__session__close" ],
    [ "remote_rpc_thread_params", "structremote__rpc__thread__params.html", "structremote__rpc__thread__params" ]
];